/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from "react-native";

const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    colors: {
      background: "#121212",
      primary: "#539DF3",
      steamColor: "#1671d9ff",
      secondary: "#1E1E1E",
      white: "#FFFFFF",
      strokeSecondarySoft: "#676D75",
      strokePrimarySoft: "#232323",
      error: "#FF4D4F",
      warning: "#FFA500",
      success: "#52C41A",
      dark: "#000000",
      blue: "#4A90E2",

      onPrimaryHigh: "#FFFFFF",
      onPrimaryMedium: "#A9AFEF",
      onSecondaryHigh: "#FFFFFF",
      onSecondaryMedium: "#999999",
      onSuccessHigh: "#EFF7ED",
      onSuccessMedium: "#9ED094",
      onErrorHigh: "#FFFFFF",
      onErrorMedium: "#F6D6D4",
      primarySoft: "#535FDF",
      onPrimarySoftHigh: "#FFFFFF",
      onPrimarySoftMedium: "#A9AFEF",
      tertiary: "#D9D9D9",
      secondarySoft: "#808080",
      onSecondarySoftHigh: "#F2F2F2",
      onSecondarySoftMedium: "#CCCCCC",
      successSoft: "#EFF7ED",
      onSuccessSoftHigh: "#25471F",
      onSuccessSoftMedium: "#4B8E3E",
      warningContainer: "#FCF6E8",
      errorSoft: "#FDF3F2",
      onErrorSoftHigh: "#80201A",
      onErrorSoftMedium: "#D4362B",
      containerPrimary: "#FFFFFF",
      onContainerPrimaryHigh: "#FFFFFF",
      onContainerPrimaryMedium: "#A9AFEF",
      containerSecondary: "#FFFFFF",
      onContainerSecondaryHigh: "#F2F2F2",
      onContainerSecondaryMedium: "#CCCCCC",
      containerSuccess: "#F6FAF4",
      onContainerSuccessHigh: "#386B2E",
      onContainerSuccessMedium: "#5DB14E",
      containerError: "#FBEBEA",
      onContainerErrorHigh: "#80201A",
      onContainerErrorMedium: "#D4362B",
      surface: "#F7F7F7",
      onSurfaceHigh: "#080808",
      onSurfaceMedium: "#333333",
      onDisabledSurface: "#B2B2B2",
      disabledSurface: "#E5E5E5",
    },
  },
  dark: {
    colors: {
      background: "#0D0D0D",
      primary: "#2A2E43",
      secondary: "#F2F2F2",
      white: "#1E1E1E",
      strokeSecondarySoft: "#E0E0E0",
      error: "#FF4D4F",
      warning: "#FFA500",
      success: "#52C41A",
      dark: "#FFFFFF",
      blue: "#4A90E2",
      steamColor: "#297bd7ff",

      onPrimaryHigh: "#F2F3FD",
      onPrimaryMedium: "#BEC3F3",
      onSecondaryHigh: "#1A1A1A",
      onSecondaryMedium: "#666666",
      onSuccessHigh: "#0A1207",
      tertiary: "#D9D9D9",
      onSuccessMedium: "#25471F",
      onErrorHigh: "#FFFFFF",
      onErrorMedium: "#F6D6D4",
      primarySoft: "#535FDF",
      onPrimarySoftHigh: "#D4D7F7",
      onPrimarySoftMedium: "#101656",
      secondarySoft: "#808080",
      onSecondarySoftHigh: "#F7F7F7",
      onSecondarySoftMedium: "#B3B3B3",
      successSoft: "#13240F",
      onSuccessSoftHigh: "#DFEFDC",
      onSuccessSoftMedium: "#9ED094",
      warningContainer: "#2E2206",
      errorSoft: "#80201A",
      onErrorSoftHigh: "#F6D6D4",
      onErrorSoftMedium: "#EEAEAA",
      containerPrimary: "#080B2C",
      onContainerPrimaryHigh: "#D4D7F7",
      onContainerPrimaryMedium: "#101656",
      containerSecondary: "#1A1A1A",
      onContainerSecondaryHigh: "#F7F7F7",
      onContainerSecondaryMedium: "#B3B3B3",
      containerSuccess: "#13240F",
      onContainerSuccessHigh: "#EFF7ED",
      onContainerSuccessMedium: "#BFE0B8",
      containerError: "#551511",
      onContainerErrorHigh: "#F6D6D4",
      onContainerErrorMedium: "#EEAEAA",
      surface: "#0D0D0D",
      onSurfaceHigh: "#F2F2F2",
      onSurfaceMedium: "#CCCCCC",
      onPrimary: "#FFFFFF",
      onDisabledSurface: "#0B1D5B",
      disabledSurface: "#060E2D06",
      strokePrimarySoft: "#535FDF",
    },
  },
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: "system-ui",
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: "ui-serif",
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: "ui-rounded",
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
